spring:
  application:
    name: DepartmentManage
  datasource:
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: YOUR_PASSWORD_HERE
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 28000
      pool-name: MySpringBootHikariPool
  # ファイルアップロードの最大サイズ設定
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


# MyBatis 設定
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # キャメルケース変換の有効化 ---> MyBatis による自動マッピング
    map-underscore-to-camel-case: true

# トランザクション管理ログレベルを debug に設定
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

# クラウドサービス情報の 3 項目を設定
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucket-name: YOUR_BUCKET_NAME
    region: YOUR_REGION_NAME

